  - name: install beats
    hosts: webservers
    become: true
    tasks:

    #
    # filebeat installation
    #
      - name: Downloading filebeat
        command: curl -L -O https://artifacts.elastic.co/downloads/beats/filebeat/filebeat-7.4.0-amd64.deb

      - name: Installing filebeat
        command: dpkg -i /home/azadmin/filebeat-7.4.0-amd64.deb

      - name: Copying filebeat-configuration.yml to target VMs
        copy:
          src: /etc/ansible/files/filebeat-configuration.yml
          dest: /etc/filebeat/filebeat-configuration.yml

      - name: Enabling filebeat modules
        command: filebeat modules enable system

      - name: Setting up filebeat
        command: filebeat setup

      - name: Starting filebeat
        command: service filebeat start

    #
    # metric beat installation
    #
      - name: Downloading metricbeat
        command: curl -L -O https://artifacts.elastic.co/downloads/beats/metricbeat/metricbeat-7.4.0-amd64.deb

      - name: Installing metricbeat
        command: dpkg -i /home/azadmin/metricbeat-7.4.0-amd64.deb

      - name: Copying metricbeat-configuration.yml to target VMs
        copy:
          src: /etc/ansible/files/metricbeat-configuration.yml
          dest: /etc/metricbeat/metricbeat.yml

      - name: Enabling metricbeat modules
        command: metricbeat modules enable docker

      - name: Setting up metricbeat
        command: metricbeat setup

      - name: Starting metricbeat
        command: service metricbeat start